### ISSUE TITLE
HUD animation is too fast

### ISSUE THREAD

**Issue by twhitt14** [relatedcode/ProgressHUD#100]
The HUD shrink & fade in animation is jarring & feels much faster than the native iOS alert controller. It would be awesome to let us control the timing & animation curve if we want.

BTW thank you for this sweet HUD framework. I like it a lot.

**Comment by relatedcode** [comment]
We have the optional `delay:` parameter to set the timeout. Something like this:

```
ProgressHUD.showSucceed("Some text", delay: 3.0)
```

```
ProgressHUD.show("Some text", icon: .heart, delay: 1.0)
```

Sorry for the long-waiting code fix. :)
