### ISSUE TITLE
Error installing ProgressHUD

### ISSUE THREAD

**Issue by dalugoda** [relatedcode/ProgressHUD#105]
[!] Error installing ProgressHUD
[!] /usr/bin/git clone https://github.com/relatedcode/ProgressHUD.git /var/folders/2t/yqz6yn6d7bj0j__lpc6f4m440000gn/T/d20200902-86706-vvv43c --template= --single-branch --depth 1 --branch v2.51

**Comment by xusion** [comment]
我也遇到，坐等解决

**Comment by dalugoda** [comment]
I sorted out this updating the pod file to install with a previous commit.

`pod 'ProgressHUD', :git => 'https://github.com/relatedcode/ProgressHUD.git', :commit => '83c3801e9aa69be157a47c40cdd8702bfaf29213'`

**Comment by relatedcode** [comment]
@dalugoda Sorry, but the previous versions are not supported any more. The earliest available version is 2.70
