### ISSUE TITLE
Disable underlying view(s) and set the tintAdjustmentMode to dimmed

### ISSUE THREAD

**Issue by gargs** [relatedcode/ProgressHUD#107]
Thanks for making this! I was wondering if it is possible to use the current code to disable user interaction on underlying views and to dim the tint on controls just like native alerts and modals. Being able to do this selectively would be awesome as well!

**Comment by relatedcode** [comment]
@gargs If I understand your question right, then this is what you need:

`ProgressHUD.show(nil, interaction: false)`

**Comment by gargs** [comment]
Hi @relatedcode! Thanks for the quick reply! That's what I want, but also be able to change the tint color on controls (navigation bar buttons, etc.) to .dimmed.

**Comment by relatedcode** [comment]
Please customize the `colorBackground` value.
