### ISSUE TITLE
Misaligned HUD on iPad in split screen

### ISSUE THREAD

**Issue by massimobio** [relatedcode/ProgressHUD#113]
On iPad in split screen the HUD appears centered in the device's screen rather than in the app window.

<img width="1166" alt="Screen Shot 2021-04-04 at 3 24 13 PM" src="https://user-images.githubusercontent.com/240599/113519395-da2de180-9559-11eb-8d5f-335abac9d6a6.png">

To enable split screen in the demo app all 4 device orientations should be enabled:
<img width="241" alt="Screen Shot 2021-04-04 at 3 26 42 PM" src="https://user-images.githubusercontent.com/240599/113519450-401a6900-955a-11eb-9e31-396d71217d78.png">

**Comment by NigelGee** [comment]
I reported this over two year’s ago

**Comment by massimobio** [comment]
I made a PR #114 for this issue.

**Comment by relatedcode** [comment]
![screenshot](https://user-images.githubusercontent.com/5425762/208265898-5b026953-77e6-4104-a32b-d993fda120eb.png)
