### ISSUE TITLE
How to display it at the top level of the view

### ISSUE THREAD

**Issue by anwent** [relatedcode/ProgressHUD#116]
I use `UIPresentationController`

As shown in the picture, I call the `ProgressHUD.show()` in `LoginPopupWindow`

But it is covered
What should I do？
please
![截屏2021-04-30 下午9 21 33](https://user-images.githubusercontent.com/15354932/116701494-8a2c2880-a9fa-11eb-948f-5e57c12a1fa7.png)

**Comment by glennposadas** [comment]
I'm experiencing the same bug. Have you solved this?

**Comment by glennposadas** [comment]
I've fixed this after so many hours! I'll submit a new PR today or tom.

**Comment by relatedcode** [comment]
@anwent Could you please provide me a demo code to check the situation by myself? Thanks!

**Comment by relatedcode** [comment]
It seems to be obsolete now.
