### ISSUE TITLE
UserInteraction_Enabled

### ISSUE THREAD

**Issue by piyushpatil** [relatedcode/ProgressHUD#118]
How does blocking user interaction in ProgressHUD

**Comment by glennposadas** [comment]
@piyushpatil in your AppDelegate, you could set all the hud settings. Like this in particular: user interaction, like so:

`ProgressHUD.allowInteraction = false`

**Comment by glennposadas** [comment]
Requesting to close this, @relatedcode

**Comment by relatedcode** [comment]
@piyushpatil You can enable/disable the user interaction by using the `interaction: Bool` parameter. Which is available for all the public methods. Like this:

`ProgressHUD.showSucceed("Some text", interaction: false)`

**Comment by relatedcode** [comment]
@glennposadas Unfortunately the `ProgressHUD.allowInteraction = false` is not yet implemented. You need to define the `interaction: Bool` parameter all the time when you need it.
