### ISSUE TITLE
How to disable userIntraction while showing progress view.

### ISSUE THREAD

**Issue by QaziAmmar** [relatedcode/ProgressHUD#122]

**Comment by steve7688** [comment]
I doubt this too

**Comment by relatedcode** [comment]
@QaziAmmar The user interaction is disabled by default when you are using the `showProgress` method. However, you can always override the user interaction behavior by using the `interaction: Bool` parameter. Like this:

`ProgressHUD.showProgress(0.1, interaction: true)`
