### ISSUE TITLE
Can not show immediately another HUD after dismissing previous one

### ISSUE THREAD

**Issue by kishanios123** [relatedcode/ProgressHUD#123]
The below code is not showing the Second HUD.

`
ProgressHUD.show("First Hud...",interaction: false)
        DispatchQueue.main.asyncAfter(deadline: .now()+4.0) {
            ProgressHUD.dismiss()
            ProgressHUD.show("Second Hud...",interaction: false)
            DispatchQueue.main.asyncAfter(deadline: .now()+4.0) {
                ProgressHUD.dismiss()
            }
        }
`

**Comment by SynthesOne** [comment]
> The below code is not showing the Second HUD.
> 
> `ProgressHUD.show("First Hud...",interaction: false) DispatchQueue.main.asyncAfter(deadline: .now()+4.0) { ProgressHUD.dismiss() ProgressHUD.show("Second Hud...",interaction: false) DispatchQueue.main.asyncAfter(deadline: .now()+4.0) { ProgressHUD.dismiss() } }`

Hi, were you able to correct this behavior?

I keep getting the same error.

**Comment by relatedcode** [comment]
We have the `.remove()` function to dismiss the HUD immediately. Something like this:

```
ProgressHUD.remove()
```

Sorry for the long-waiting code fix. :)
