### ISSUE TITLE
ProgressHUD not visible when call .show() method

### ISSUE THREAD

**Issue by TopIvanAbramov** [relatedcode/ProgressHUD#124]
ProgressHUD view is not on top it is showed in between:
UIWindowScene (Foreground active) -> UIWindow -> UIView -> ProgressHUD -> TopViewController

But when I cal show method second time it is showed corretly

**Comment by relatedcode** [comment]
@TopIvanAbramov Could you please provide me a demo code to check the situation by myself? Thanks!

**Comment by relatedcode** [comment]
It seems to be obsolete now.
