### ISSUE TITLE
Xcode 14 Beta 6 SwiftUI preview doesn't work

### ISSUE THREAD

**Issue by alexanderkhitev** [relatedcode/ProgressHUD#130]
Hello,
I faced `SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x000060004e28fd50):'ProgressHUD'>)` error in Xcode Canvas SwiftUI preview in Xcode 14 Beta 4. Does anyone know how to solve it or maybe have a fix for it? Thanks

**Comment by lotz** [comment]
I am seeing this issue too. There is [a long thread on Apple's Developer Forums](https://developer.apple.com/forums/thread/707569) as well.

One package was fixed by removing "`.static`" from the `Package.swift` files?
- https://github.com/microsoft/appcenter-sdk-apple/pull/2433/files

**Comment by relatedcode** [comment]
@alexanderkhitev Please let me know if the problem still exists. Thanks!

**Comment by lotz** [comment]
@relatedcode Thanks for checking in. I can confirm that this is no longer an issue with Xcode 14.2. I am able to use SwiftUI previews with either ProgressHUD 13.6.1 or 13.6.2.

The issue appears to have been fixed on the Xcode side, as I was still getting the errors with Xcode 14.1 regardless of ProgressHUD version.

**Comment by relatedcode** [comment]
@lotz Awesome! Thanks! :)
