### ISSUE TITLE
Not showing on some iOS 13 versions

### ISSUE THREAD

**Issue by TobiasRuano** [relatedcode/ProgressHUD#131]
I'm having a weird bug. The ProgressHUD is not showing on iOS versions like 13.3.1 or 13.7 but it works OK in iOS 13.0 or newer versions like 14 15 and 16.

Has anyone experienced something similar?

Running Xcode 13.4.1 with the latest version of ProgressHUD (13.6)

**Comment by relatedcode** [comment]
@TobiasRuano Can you please provide me some more details here? Thanks!

**Comment by relatedcode** [comment]
It seems to be obsolete now.
