### ISSUE TITLE
ProgressHUD.colorHUD can't work 

### ISSUE THREAD

**Issue by TushningJJ** [relatedcode/ProgressHUD#141]
because _UIVisualEffectBackdropView has a color ,and above toolbarHUD .

**Comment by relatedcode** [comment]
I am not sure if I 100% understand the situation here. Please explain. Thanks!

**Comment by TushningJJ** [comment]
is "ProgressHUD.colorHUD"  be used to change the color of hud?   i want change the color of  the  hud ,but  i fand it  unable to work correctly, so when i  debug view hierarchy, i  find there has a view named "_UIVisualEffectBackdropView" ,it has a color ,and above toolbarHUD view. 
I don't know if I misunderstood the colorHUD

**Comment by twototwoto** [comment]
I am not sure whether you want to change "toolbarHUD?.backgroundColor = colorHUD" to "toolbarHUD?.barTintColor = colorHUD" or not?

**Comment by relatedcode** [comment]
### This is the original color setup:

![original](https://github.com/relatedcode/ProgressHUD/assets/5425762/10e37b37-ec43-4c3a-85b1-7eebb71924b4)

**Comment by relatedcode** [comment]
### And this is when you recolor everything:

![recolor](https://github.com/relatedcode/ProgressHUD/assets/5425762/5a446c62-fe8b-4988-9d36-73de1678b4be)
