### ISSUE TITLE
if dismiss and then  show again immediately , it will not show.

### ISSUE THREAD

**Issue by TushningJJ** [relatedcode/ProgressHUD#143]
ProgressHUD.show()
      
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 2) {

            ProgressHUD.dismiss()
            
            DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.04) {
                ProgressHUD.showError()
            }
          // DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.05) {
            //    ProgressHUD.showError()
            // }
        }

if  i want show again ,i should set  greater than 0.05 TimeInterval ,otherwise is will not show .

**Comment by relatedcode** [comment]
Please use the ProgressHUD.remove() instead of the ProgressHUD.dismiss() if you plan to re-display the ProgressHUD immediately. Thanks!
