### ISSUE TITLE
cocoapods can't be use

### ISSUE THREAD

**Issue by KavinKily** [relatedcode/ProgressHUD#144]
pod install              
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "ProgressHUD":
  In Podfile:
    ProgressHUD (~> 13.7.2)

Specs satisfying the `ProgressHUD (~> 13.7.2)` dependency were found, but they required a higher minimum deployment target

**Comment by relatedcode** [comment]
ProgressHUD is an iOS 13.0+ library. I guess this could be the problem here. Please let me know if you are trying to use ProgressHUD in an iOS 13.0+ code, and you are still experiencing the issue.
