### ISSUE TITLE
Hide and Show progress bar inside TableViewCells

### ISSUE THREAD

**Issue by Arshad-iOSDeveloper** [relatedcode/ProgressHUD#145]
I have TableView cells with custom views. I need to call multiple api calls at a time and i need to show progress bar in every view inside cell. Once i get data from api, need to hide progress bar.
Until the api is getting called need to show multiple progress bars inside each tableview cells.
![Tableview](https://github.com/relatedcode/ProgressHUD/assets/88126365/39536ec7-c0a6-4c37-bec9-feffcb289fc5)

**Comment by relatedcode** [comment]
This is something you cannot do with ProgressHUD. Sorry.
