### ISSUE TITLE
Change color by ProgressHUD.colorHUD works wrong

### ISSUE THREAD

**Issue by crash481** [relatedcode/ProgressHUD#148]
Hello, when I do
ProgressHUD.colorHUD = .black
Then I need background color will be black. But it is not black
It is light gray, see below
![Simulator Screenshot - iPhone 11 Pro - 2023-10-04 at 02 51 33](https://github.com/relatedcode/ProgressHUD/assets/7975051/b81d6fff-2ded-404c-9b83-a312abe538b8)

Here is same issue, but you close it without solution.
 https://github.com/relatedcode/ProgressHUD/issues/141

**Comment by relatedcode** [comment]
@crash481 You're absolutely right. The HUD view is implemented using UIToolbar, and due to the inherent limitations of UIToolbar's rendering capabilities, it can't be displayed in pure black. This is a constraint of the UIKit framework itself.

**Comment by daksheshtalaviya** [comment]
@crash481 Your solution is ready: #176
