### ISSUE TITLE
ProgressHUD not working in 13.8.1 and up

### ISSUE THREAD

**Issue by appfrilans** [relatedcode/ProgressHUD#149]
Progress views do not appear anymore. Seemingly starting from version 13.8.1

`ProgressHUD.show("testing") `

does nothing anymore, at least testing on an iOS 17 simulator iPad. Same code worked before and does so with 13.8.0

Could it be related to "Added multi-window support: custom window can be defined now."?

"Full" code:

```
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        ProgressHUD.show("Testar")
    }
```

**Comment by relatedcode** [comment]
@appfrilans Thanks for your feedback. Could you please check version 13.8.4 and let me know if the issue still exists?

**Comment by appfrilans** [comment]
> @appfrilans Thanks for your feedback. Could you please check version 13.8.4 and let me know if the issue still exists?

Seems to solved the issue! Thanks!
