### ISSUE TITLE
`Unexpectedly found nil` when showing banner

### ISSUE THREAD

**Issue by kashif-izhar** [relatedcode/ProgressHUD#150]
`ProgressHUD/ProgressHUD+Banner.swift:117: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value`

I am getting above crash when trying to show a banner with below code:

`ProgressHUD.showBanner("Ghosting On", "Last image will now show to position your next shot", delay: 8.0)`

Error leads to the following line in **ProgressHUD+Banner.swift** file
```
extension ProgressHUD {
	private func resizeBanner() {
		**let widthBanner = main.frame.width - 32**
```

**Comment by relatedcode** [comment]
@kashif-izhar Fixed. Thanks for the feedback. Please check the version [13.8.6](https://github.com/relatedcode/ProgressHUD/releases/tag/13.8.6)

**Comment by kashif-izhar** [comment]
@relatedcode  Thank you very much! for the quick resolution
