### ISSUE TITLE
SPM: Manifest property 'defaultLocalization' not set; it is required in the presence of localized resources

### ISSUE THREAD

**Issue by callo90** [relatedcode/ProgressHUD#167]
Hey,

I'm getting this error after updating to the latest `v14.1.2`, I'm using SPM.

If the library has any localized resource, this `defaultLocalization: "en"` must be added to the Package.

**Comment by relatedcode** [comment]
@callo90 Awesome! Thanks!

Would you please provide me the full, modified file? Here, or as a PR.

Thanks! :)

**Comment by ebsi-ffoster** [comment]
Commenting as a +1 to the issue

**Comment by relatedcode** [comment]
@zdravkin Thank you for your help! :)

**Comment by callo90** [comment]
Sweet, PR merged. Please create a new release.
