### ISSUE TITLE
Cannot install with CocoaPod

### ISSUE THREAD

**Issue by samwize** [relatedcode/ProgressHUD#50]
The podspec in http://cocoapods.org/?q=ProgressHUD indicate there is a tag v1.3, but that is missing.

Can you tag your branch or update podspec?

**Comment by samwize** [comment]
Sorry. Am I using the wrong pod? On CocoaPods it says there is v1.3, but I don't see the 1.3 tag in this repo.

    pod 'ProgressHUD', '~> 1.3'

**Comment by k06a** [comment]
I don't know why @relatedcode wiped out this repo. Now all cocoapods previous versions become unusable until we find any fork and use it...

**Comment by gvaish** [comment]
@samwize   Use this: https://github.com/gvaish/ProgressHUD
