### ISSUE TITLE
Landscape orientation bug on iOS 7 

### ISSUE THREAD

**Issue by laurenz-glueck** [relatedcode/ProgressHUD#56]
If I use ProgressHUD on **iOS 7** in *landscape* mode, the UI is still in *portrait* mode...
Bug detected on iPhone and iPad (iOS 8 working fine...)

![ios simulator screen shot 21 03 2015 15 15 27](https://cloud.githubusercontent.com/assets/2734232/6765366/2508725e-cfdd-11e4-8101-7849ef469b0b.png)

**Comment by relatedcode** [comment]
The code is iOS 8 only.

**Comment by laurenz-glueck** [comment]
@relatedcode No iOS 7 support? really?!

**Comment by relatedcode** [comment]
No. Really.

**Comment by laurenz-glueck** [comment]
@relatedcode I played around with it and now have a code snippet that will fix that for iOS 7... Should I push it?
