### ISSUE TITLE
CocoaPods package

### ISSUE THREAD

**Issue by dragouf** [relatedcode/ProgressHUD#59]
There is a package on CocoaPods. Unfortunately it doesn't work because branch v1.3 is missing in this github repository.

Maybe by just adding it it should solve this problem ?

**Comment by groschovskiy** [comment]
This is bad idea!

**Comment by dragouf** [comment]
??

**Comment by gvaish** [comment]
@dragouf  Use this: https://github.com/gvaish/ProgressHUD
