### ISSUE TITLE
Why did you break Pod spec?

### ISSUE THREAD

**Issue by gvaish** [relatedcode/ProgressHUD#61]

**Comment by gvaish** [comment]
Why did you delete my description and the details?

**Comment by warpling** [comment]
Do you mind giving people some sort of answer? You closed almost a dozen identical issues  (#59, #52, #50, #45, #30, #34, #35, #28, #24, #13) without providing any additional information.

**Comment by gvaish** [comment]
@warpling Ok... I fixed it. Finally here: https://github.com/gvaish/ProgressHUD

**Comment by warpling** [comment]
@relatedcode why did you delete my and @gvaish's comment? Sorry if it came across as hostile—just an honest question.
