### ISSUE TITLE
Unable to install using cocoapods

### ISSUE THREAD

**Issue by thundertrick** [relatedcode/ProgressHUD#66]
This is a really nice HUD. But when I install it using `pod 'ProgressHUD', '~> 1.3'`, the following msg shows. Is there any thing wrong here? 

    $ pod install
    Analyzing dependencies

    CocoaPods 0.39.0.beta.4 is available.
    To update use: `gem install cocoapods --pre`
    [!] This is a test version we'd love you to try.

    For more information see http://blog.cocoapods.org
    and the CHANGELOG for this version http://git.io/BaH8pQ.

    Downloading dependencies
    Installing ProgressHUD (1.3)

    [!] Error installing ProgressHUD
    [!] /usr/bin/git clone https://github.com/relatedcode/ProgressHUD.git XXXX/myAPP/Pods/ProgressHUD --single-branch --depth 1 --branch v1.3

    Cloning into 'XXXX/myAPP/Pods/ProgressHUD'...

    warning: Could not find remote branch v1.3 to clone.

    fatal: Remote branch v1.3 not found in upstream origin

**Comment by gvaish** [comment]
@thundertrick Use this: https://github.com/gvaish/ProgressHUD

This is what happened earlier: https://github.com/relatedcode/ProgressHUD/issues/61

**Comment by dimohamdy** [comment]
+1

**Comment by s-zl** [comment]
$pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing ProgressHUD (1.3)

[!] Error installing ProgressHUD
[!] /usr/bin/git clone https://github.com/relatedcode/ProgressHUD.git /var/folders/cx/pkx_skfx68z9bgy5rzk1r7800000gn/T/d20151028-2804-1rb7qbg --single-branch --depth 1 --branch v1.3

Cloning into '/var/folders/cx/pkx_skfx68z9bgy5rzk1r7800000gn/T/d20151028-2804-1rb7qbg'...
warning: Could not find remote branch v1.3 to clone.
fatal: Remote branch v1.3 not found in upstream origin
Unexpected end of command stream

**Comment by liuzhecodekiller** [comment]
+1
