### ISSUE TITLE
Image resources

### ISSUE THREAD

**Issue by iksudnik** [relatedcode/ProgressHUD#71]
Hi!

I'm using you library in my Swift 3 project as a pod. It's appeared that images from the ProgressHUD.bundle doesn't want to load. My workaround looks like this
```objective-c
#define HUD_RESOURCE_BUNDLE [NSBundle bundleWithURL:[[NSBundle bundleForClass:[self class]] URLForResource:@"ProgressHUD" withExtension:@"bundle"]]

#define HUD_IMAGE_SUCCESS [UIImage imageNamed:@"progresshud-success.png" inBundle:HUD_RESOURCE_BUNDLE compatibleWithTraitCollection:nil]

#define HUD_IMAGE_ERROR [UIImage imageNamed:@"progresshud-error.png" inBundle:HUD_RESOURCE_BUNDLE compatibleWithTraitCollection:nil]
```

But also it would be great to have a possibility to set up appearance globally.
Thanks!

**Comment by bigearsenal** [comment]
I also have this issue, so where to put your workaround code?

**Comment by LeaderBoy** [comment]
I also have this issue

**Comment by LeaderBoy** [comment]
I solved the problem

dispatch_async(dispatch_get_main_queue(), ^{
        NSBundle *bundle = [NSBundle bundleForClass:[ProgressHUD class]];
        NSString *path = [[bundle resourcePath] stringByAppendingPathComponent:@"progresshud-error"];
        UIImage *image = [UIImage imageWithContentsOfFile:path];
		[[self shared] hudCreate:status image:image spin:NO hide:YES interaction:YES];
	});

**Comment by dhmoon91** [comment]
@bigearsenal 
On Xcode go to Pods-> ProgressHUD -> ProgressHUD.h

You should see the #define statements at top.

**Comment by relatedcode** [comment]
@iksudnik @bigearsenal @LeaderBoy @dhmoon91 @wilferrel Fixed. Sorry for the delay. :)
