### ISSUE TITLE
Set timeout

### ISSUE THREAD

**Issue by erayalparslan** [relatedcode/ProgressHUD#89]
It'd be great to be able to set timeout to dismiss the hud. Im saying it as an improvement.

**Comment by hj4859199** [comment]
I think so too

**Comment by IKorabel** [comment]
I totally agree with you!

**Comment by goalguy10** [comment]
Any update on this?

**Comment by mazharulbelal** [comment]
Any update about timeout to dismiss?

**Comment by relatedcode** [comment]
We have the optional `delay:` parameter to set the timeout. Something like this:

```
ProgressHUD.showSucceed("Some text", delay: 3.0)
```

```
ProgressHUD.show("Some text", icon: .heart, delay: 1.0)
```

Sorry for the long-waiting code fix. :)
