### ISSUE TITLE
Stays Too Long

### ISSUE THREAD

**Issue by wiggleforlife** [relatedcode/ProgressHUD#91]
For what I'm making with this, the popup lasts too long. I searched the ProgressHUD.m and .h, but I couldn't find anything. Is there a way?

**Comment by luchi17** [comment]
I have the same issue:(

**Comment by relatedcode** [comment]
We have the optional `delay:` parameter to set the timeout. Something like this:

```
ProgressHUD.showSucceed("Some text", delay: 3.0)
```

```
ProgressHUD.show("Some text", icon: .heart, delay: 1.0)
```

Sorry for the long-waiting code fix. :)
